version: '3'
services:
  web:
    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "app.py"]
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: week1
